---

- block:
    - name: Switch production symlink
      file:
        src: '{{ djsite_release_directory }}'
        dest: '{{ djsite_app_directory }}/production'
        state: link

    - name: Trigger application reload
      file:
        name: '{{ djsite_touch_reload_file }}'
        owner: '{{ djsite_touch_reload_owner }}'
        group: '{{ djsite_touch_reload_group }}'
        mode: '{{ djsite_touch_reload_mode }}'
        state: touch
  become: yes
  become_user: root
