---

- block:
    - name: Check variables
      assert:
        that:
          - djsite_configure_tasks_file is defined
          - djsite_database_host is defined
          - djsite_database_name is defined
          - djsite_database_password is defined
          - djsite_database_user is defined
          - djsite_domains is defined
          - djsite_environment_variables is defined
          - djsite_instance_name is defined
          - djsite_is_master is defined
          - djsite_max_releases|int > 0
          - djsite_release_mode in djsite_release_modes
          - djsite_release_timestamp is defined
          - djsite_repository_url is defined
          - djsite_role_action in djsite_role_actions
          - djsite_secret_key|length > 30
          - djsite_settings_module is defined
          - djsite_standalone is defined
          - djsite_superuser.email is defined
          - djsite_superuser.name is defined
          - djsite_superuser.password is defined
          - djsite_update_tasks_file is defined
          - djsite_virtualenv_tasks_file is defined

    - name: Set release directory and detect if repository is local
      set_fact:
        djsite_release_directory: "{{ djsite_app_directory }}/{{ (djsite_release_mode == 'direct')|ternary('test', 'releases/'+djsite_release_timestamp) }}"
        djsite_repository_is_local: "{{ ':' not in djsite_repository_url }}"

    - name: Ensure version is defined if repository is remote
      assert:
        that:
          - djsite_repository_version is defined
      when: not djsite_repository_is_local|bool

    - name: Ensure SSH variables are defined if repository is remote or has private requirements
      assert:
        that:
          - djsite_repository_host is defined
          - djsite_repository_key is defined
          - djsite_ssh_key_private is defined
          - djsite_ssh_key_public is defined
      when: not djsite_repository_is_local|bool or djsite_has_private_requirements|bool

    - name: Show repository variables
      debug:
        var: '{{ item }}'
      loop:
        - djsite_release_directory
        - djsite_repository_is_local
        - djsite_repository_version
  tags: always
