---

- block:
    - name: Read application configuration file
      command:
        cat {{ djsite_app_directory }}/source/config.yml
      changed_when: no
      check_mode: no
      register: _djsite_config

    - name: Get application Git log
      command: >
        git log -n 20
      args:
        chdir: '{{ djsite_app_directory }}/source'
      changed_when: no
      check_mode: no
      failed_when: >
        _djsite_git_log is failure and
        'not a git' not in _djsite_git_log.stderr|lower
      register: _djsite_git_log

    - name: Set application variables
      set_fact:
        djsite_config: '{{ _djsite_config.stdout|from_yaml }}'
        djsite_git_log: '{{ _djsite_git_log.stdout_lines }}'

    - name: Show application configuration
      debug:
        var: djsite_config

    - name: Check application configuration
      assert:
        that:
          - djsite_config.configuration_templates is defined
          - djsite_config.custom_applications is defined
          - djsite_config.source_path is defined

    - name: Find required Python
      command:
        which {{ djsite_config.python_executable|default(djsite_default_python_executable) }}
      changed_when: no
      check_mode: no
      register: _djsite_python_executable

    - name: Set Python library path
      set_fact:
        djsite_python_executable: '{{ _djsite_python_executable.stdout }}'
        djsite_python_library: "{{ _djsite_python_executable.stdout|regex_replace('bin', 'lib') }}"

    - name: Show Detected Python executable
      debug:
        var: djsite_python_executable

    - name: Show Detected Python library
      debug:
        var: djsite_python_library
  become: yes
  become_user: '{{ djsite_daemon_user }}'
  tags: always
