# Action

---

- block:
    - import_tasks: deploy-release.yml
    - import_tasks: finalize-release.yml

    - block:
        - name: Reset the unit-tests coverage report
          command: >
            {{ djsite_app_directory }}/test/venv/bin/coverage erase
          args:
            chdir: '{{ djsite_app_directory }}/test/server'

        - name: Unit-test the application
          command: >
            {{ djsite_app_directory }}/test/venv/bin/coverage run {{ djsite_coverage_options|join(' ') }}
            manage.py test {{ djsite_config.custom_applications|join(' ') }} {{ djsite_test_options }}
          args:
            chdir: '{{ djsite_app_directory }}/test/server'

        - name: Generate the unit-tests coverage report
          command: >
            {{ djsite_app_directory }}/test/venv/bin/coverage
            html -d {{ djsite_app_directory }}/test/cover/
          args:
            chdir: '{{ djsite_app_directory }}/test/server'

        - name: Copy the unit-tests coverage report in the local machine
          synchronize:
            src: '{{ djsite_app_directory }}/test/cover/'
            dest: '{{ djsite_repository_url }}/{{ djsite_config.source_path }}/cover/'
            archive: yes
            checksum: yes
            delete: yes
            mode: pull
          when: djsite_repository_is_local|bool

        - name: Retrieve unit-tests coverage
          shell: >
            {{ djsite_app_directory }}/test/venv/bin/coverage \
            report | tail -n 1 | sed -r 's:.*\s+([0-9]+)%:\1:'
          args:
            chdir: '{{ djsite_app_directory }}/test/server'
          register: _djsite_coverage

        - debug:
            msg: 'Coverage {{ _djsite_coverage.stdout }}% (min {{ djsite_coverage_minimum }}%)'

        - name: Ensure unit-tests coverage is sufficient
          fail:
            msg: 'Unit-tests coverage of {{ _djsite_coverage.stdout }}% is under the minimum set at {{ djsite_coverage_minimum }}%'
          when: _djsite_coverage.stdout|int < djsite_coverage_minimum|int
      tags: unit-test

  become: yes
  become_user: '{{ djsite_daemon_user }}'
  tags: unit-test
  when: djsite_is_master|bool
