---

- name: restart cron
  service:
    name: cron
    state: restarted
  become: yes

- name: restart celery workers
  supervisorctl:
    name: '{{ djsite_instance_name }}-celery-{{ item.value.name }}'
    state: restarted
  become: yes
  loop_control:
    label: '{{ item.value.name }}'
  with_dict: '{{ djsite_celery_workers }}'

- name: restart application process
  supervisorctl:
    name: '{{ djsite_instance_name }}-process:'
    state: restarted
  become: yes
  when: djsite_process_enabled|bool
